const database = [
    {
        sectorName: "البلدية",
        sectorCode: "P001",
        sectorIcon: "icon-5.svg",
        sectorN: "municipality",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الصحة",
        sectorCode: "B201",
        sectorIcon: "icon-3.svg",
        sectorN: "health",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "التعليم",
        sectorCode: "K503",
        sectorIcon: "icon-2.svg",
        sectorN: "education",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "النقل والخدمات اللوجستية",
        sectorCode: "m907",
        sectorIcon: "icon-4.svg",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الصناعة",
        sectorCode: "P001",
        sectorIcon: "icon-11.svg",
        sectorN: "trade",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الاتصالات وتقنية المعلومات",
        sectorCode: "P001",
        sectorIcon: "icon-6.svg",
        sectorN: "telecom",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "السياحة",
        sectorCode: "t102",
        sectorIcon: "icon-1.svg",
        sectorN: "tourism",
        info: ["ترخيص عقاري", "الارشاد السياحي", "تنظيم الرحلات السياحية", "حجز وحدات الايواء", "الايواء السياحي"],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الإعلام",
        sectorCode: "P001",
        sectorIcon: "icon-8.svg",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الصناعات العسكرية",
        sectorCode: "P001",
        sectorIcon: "icon-9.svg",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الترفيه",
        sectorCode: "P001",
        sectorIcon: "icon-7.svg",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الرياضة",
        sectorCode: "P001",
        sectorIcon: "icon-12.svg",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الطاقة",
        sectorCode: "B201",
        sectorIcon: "icon-13.svg",
        sectorN: "power",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "الغذاء والدواء",
        sectorCode: "P001",
        sectorIcon: "icon-10.svg",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
];

const tbl_tourism = [
    {
        tId: "t102",
        tName: "الفنادق",
        tCode: "551011",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الفنادق التراثية",
        tCode: "551013",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق الاستشفاء",
        tCode: "551014",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق البوتيك",
        tCode: "551015",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الفلل الفندقية",
        tCode: "551023",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الشقق المخدومة",
        tCode: "551025",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "بيوت العطلات (الشاليهات)",
        tCode: "551041",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "النزل السياحية",
        tCode: "551043",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "المنتجعات",
        tCode: "551044",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "وحدات المشاركة بالوقت",
        tCode: "551060",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق الكبائن",
        tCode: "551071",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "إدارة مرافق الإيواء السياحي",
        tCode: "551081",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "المخيمات",
        tCode: "552001",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "أنشطة وكالات السياحة والسفر",
        tCode: "791101",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "تنظيم رحلات سياحية",
        tCode: "791223",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "أنشطة الأدلاء السياحيين",
        tCode: "791224",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "حجز وحدات الإيواء السياحي وتسويقها",
        tCode: "799014",
        tIcon: "icon-1.svg",
        tdesc: "",
    },

];